# Generated by Django 5.1.1 on 2024-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0002_remove_account_balance_transaction_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
            ],
        ),
    ]
