# Generated by Django 5.1.1 on 2024-11-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0003_modelmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmapping',
            name='field',
            field=models.CharField(choices=[('account', 'Account Number'), ('name', 'Transaction Description'), ('date', 'Transaction Date'), ('amount', 'Transaction Amount'), ('balance', 'Account Balance'), ('skip', 'Skip')], max_length=7),
        ),
    ]
