# Generated by Django 5.1.1 on 2024-11-23 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0004_alter_modelmapping_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spendings_tool.account')),
            ],
        ),
    ]
