# Generated by Django 5.1.1 on 2024-11-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0005_accountmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
