# Generated by Django 5.1.1 on 2024-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0007_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CA', 'Current Account'), ('SA', 'Savings Account'), ('ISA', 'Individual Savings Account(ISA)')], max_length=7),
        ),
    ]
