# Generated by Django 5.1.1 on 2024-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0008_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmapping',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
