# Generated by Django 5.1.1 on 2024-11-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0009_alter_modelmapping_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('account', 'date', 'amount', 'balance')},
        ),
    ]
