# Generated by Django 5.1.1 on 2024-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_tool', '0010_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
